### ISSUE TITLE
Recent commit adds build dependency on pkg-config

### ISSUE THREAD

**Issue by agoodney** [libusb/libusb#1096]
This commit adds pkg-config as a build dependency. Prior to this commit pkg-config was not required to build (at least on MacOS).

https://github.com/libusb/libusb/commit/50b5838183611144d1133b5a58def2f058db0e6e

After this commit, if pkg-config is not present, ./configure will error with a syntax error:

```
./configure: line 17642: syntax error near unexpected token `UMOCKDEV,'
./configure: line 17642: `		PKG_CHECK_MODULES(UMOCKDEV, umockdev-1.0 >= 0.16.0, ac_have_umockdev=yes, ac_have_umockdev=no)'
```

**Comment by tormodvolden** [comment]
Yes, this is a bit silly, because umockdev is Linux-only and the pkg-config stuff is already contained within the Linux-only part of configure.ac. But that part is always present and calls for this macro substitution. @benzea do you have an idea how to solve this?

(Actually I am surprised pkg-config was not already required on macOS, but if it isn't, it would be good to keep it that way.)

**Comment by agoodney** [comment]
Unfortunately, that is not the behavior I see.

With libusb-master (and no pkg-config) this does not work:

./bootstrap.sh
./configure

Interestingly, I had to 'make uninstall' pkg-config to get it to fail again. Just renaming pkg-config to pkg-foo was not sufficient to put the problem back.

**Comment by tormodvolden** [comment]
Yes, the maintainer runs ./bootstrap on a computer which has the autoconf pkg-config macros* (pkg.m4). The resulting configure script is very portable and can be run on all kind of build machines, whether they have pkg-config installed or not.

*) but not necessarily the pkg-config executable, because that is irrelevant at this point. However, typically the macros and the pkg-config executable are in the same distribution package.

**Comment by tormodvolden** [comment]
> Renaming pkg-config leaves the autoconf macros defined in such a way that ./bootstrap.sh can create a release ./configure that works in the absence of pkg-config.

Exactly. 
> Just renaming pkg-config to pkg-foo was not sufficient to put the problem back.

You probably saw `checking for pkg-config... no` when you ran ./configure.

**Comment by hjelmn** [comment]
Yes. If you are running bootstrap you MUST have pkg-config.

**Comment by martinling** [comment]
I was just setting up a libusb build on a new MacOS test system and ran into this.

I think this issue should be reopened. It's fine to require `pkg-config`, but neither `bootstrap.sh` nor `configure` complains if it's missing. Instead you get a cryptic syntax error from `configure` which says nothing about `pkg-config`.

If `bootstrap.sh` requires `pkg-config` then it should report an error if it doesn't find it.

**Comment by tormodvolden** [comment]
Wasn't this taken care of by commit ba69847?

**Comment by martinling** [comment]
Oh, so it was. I was checking out v1.0.26 rather than master and didn't realise this had been fixed since. :+1:
