### ISSUE TITLE
Core: USB 3.0 Bulk Stream Support 

### ISSUE THREAD

**Issue by jwrdegoede** [libusb/libusb#11]
Duplicate of libusbx issue libusbx/libusbx#144.

**Comment by matthieuheitz** [comment]
Hi !

I wasn't aware that bulk streams were only introduced in USB 3.0 until I read [this](http://www.mjmwired.net/kernel/Documentation/usb/bulk-streams.txt).
In the libusb documentation, the functions that use bulk streams (libusb_alloc_streams, libusb_transfer_set_stream_id, etc...) have a good description, but for someone new to the subject, we don't know if we can use these functions with our device, we only know that the feature was added in version 1.0.19 of libusb.
What could be nice is an explanation in the Detailed Description of the [Asynchronous Device I/O page](http://libusb.sourceforge.net/api-1.0/group__asyncio.html#ga2dd2597a76df55e8d2f3e67b9ccea959)
It would basically say that Bulk stream is a new mode introduced by USB 3.0, and that libusb supports it since 1.0.19. There could be a link to a brief description of the mode (like the first one I provided above), and a warning that says that it can't be used for USB 2.0 devices.

I'm giving you feedback because it took me some time to figure out what Bulk Transfer was, and I was very tempted of using it (the name sounds appealing, especially because I work with a device that transfers video).

Thanks ! You're doing an awesome job with libusb !
