### ISSUE TITLE
Official Nintendo Wii U Adapter 4 Port  - Possible to set USB Report Rate to higher values?

### ISSUE THREAD

**Issue by zDEFz** [libusb/libusb#336]
Hi,

We are using libusb through Zadig for  GameCube Controller Adapter for Wii U 4 Port version in wii u mode
Device ID = WUP-028
It would be cool for us to change report rate up to 1000 Hz
Unfornately we can't modify the driver because it needs a certificate.
There is already proof on concept for Linux. https://github.com/HannesMann/gcadapter-oc-kmod

But we need it on Windows as well.
What can we do? 

Many Thanks,

DEF

**Comment by HannesMann** [comment]
I've already investigated it on Windows and it can't be done, because Windows only provides a copy function to the `USB_ENDPOINT_DESCRIPTOR` struct so you can't modify the `bInterval` value. 

(https://msdn.microsoft.com/en-us/library/windows/hardware/ff539317(v=vs.85).aspx also explicitly says that "Drivers cannot change it." in regards to the `bInterval` value)

**Comment by mcuee** [comment]
>
> This is not a libusb or device driver signature (or Zadig) problem. Will
close this.
