### ISSUE TITLE
LGPL license link exception 

### ISSUE THREAD

**Issue by nxpfrankli** [libusb/libusb#497]
We are working on a BSD license tools, which use libusb.  we want to static link libusb in windows, so customer just need download a portable executive file. 

In libgit2 have linking exception.  Is it possible to add the similar exception in libusb projuct? 

https://github.com/libgit2/libgit2/blob/master/COPYING

----------------------------------------------------------------------

			LINKING EXCEPTION

 In addition to the permissions in the GNU General Public License,
 the authors give you unlimited permission to link the compiled
 version of this library into combinations with other programs,
 and to distribute those combinations without any restriction
 coming from the use of this file.  (The General Public License
 restrictions do apply in other respects; for example, they cover
 modification of the file, and distribution when not linked into
 a combined executable.)

----------------------------------------------------------------------

**Comment by LudovicRousseau** [comment]
libusb uses the GNU **LESSER** GENERAL PUBLIC LICENSE, not the GNU GENERAL PUBLIC LICENSE as used by libgit2.

I think this is a non-issue.

**Comment by nxpfrankli** [comment]
**LESSER** GPL still not allowed static link,  only allow dynamical link

**Comment by LudovicRousseau** [comment]
I don't think so. Please point the license chapter that says that.

**Comment by hjelmn** [comment]
Yeah, my understanding is that the LGPL allows even static linking. That exception in libgit2 is worded in the worst way. It allows modifications to the embedded library without ever contributing back.

**Comment by nxpfrankli** [comment]
Our legal team said software need be GPL\LGPL if static link with LGPL library.  Can you help high light section which said allow static link into NO GPL's software?

**Comment by hjelmn** [comment]
From wikipedia:

```
Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable shared library mechanism for linking". Alternatively, a statically linked library is allowed if either source code or linkable object files are provided.[2]
```

This means someone can request either the original libusb.a you used to link OR the source code used to generate it.

**Comment by hjelmn** [comment]
At least that is the way I read it.

**Comment by nxpfrankli** [comment]
Thanks, I will ask our legal\license team to comment this.  Anyway, it is good news.

**Comment by nxpfrankli** [comment]
https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic

**Comment by ceztko** [comment]
I'm sorry to resume this old issue but I want to clarify one point:

@hjelmn said:
> From wikipedia:
> "Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable shared library mechanism for linking". Alternatively, a statically linked library is allowed if either source code or linkable object files are provided.[2]"
>
> This means someone can request either the original **libusb.a** you used to link OR the source code used to generate it.

The last sentence is not entirely correct, because if you statically link libusb in your closed source software that is distributed, LGPL is also requiring you to supply `yourclosedsw.o` or `yourclosedsw.a` to anyone who is asking, so they will be able to relink the final `yourclosedsw` or `yourclosedsw.so` with a modified version of libusb. Alternatively, a relocatable binary mechanism could also work, but that's not always available. This is clearly not the same as requiring you to release the source code, as for GPL, but that's definitely something to consider when statically linking LGPL software.

I have personally coined the term for this requirement as "the hobbyist clause", and I think it's quite in contrast with the current trend of open source software, where big companies push software that is more and more complex/engineered, making this clause annoying to fulfil. That's why you see much MIT code released by the same big companies, which in the end tends to create a large ecosystem of software with very liberal licensing terms.

Still, the clause is very consistent with RMS way of thinking, which I would summarize with "You are free to use my LGPL software, but let me hack-in a modified version of my software into yours, if I want".
