### ISSUE TITLE
libusb is not working on linux kernel 4.4 and above

### ISSUE THREAD

**Issue by patrickcjh** [libusb/libusb#525]
I am using libusb in bulk transfer mode. When performing a READ operation, the libusb_bulk_transfer function returns LIBUSB_ERROR_OVERFLOW on the first and every subsequent read. However it works if I downgrade the kernel to 4.2.x. The OS is Ubuntu 14.04.

I tested on linux kernel 4.15.x on Ubuntu 18.04 and it doesn't work as well.

**Comment by tich** [comment]
Could you possibly be submitting bulk transfers that are larger than the maximum allowed transfer size? You can read the following file to see what the maximum allowed transfer size is on your machine (it's in megabytes):  /sys/module/usbcore/parameters/usbfs_memory_mb

You can also write to that file to temporarily increase the limit. Ideally though I think your application should check that limit before it starts doing bulk transfer

**Comment by patrickcjh** [comment]
In fact I use a very small packet size of 66 bytes, and still it doesn't work.

I read online that libusb depends on usbfs? Could it be usbfs being deprecated in recent kernels?

**Comment by hjelmn** [comment]
libusb does not require usbfs. It uses udev for discovery. I can take a look with one of my devices.

**Comment by patrickcjh** [comment]
Thanks @hjelmn

**Comment by dickens** [comment]
libusb does indeed depend on usbfs, which are the USB device nodes generally presented at /dev/bus/usb.

Your issue is outside of libusb as libusb only reports the overflow error that the kernel gave it.  Overflow means that the device sent more data than the host was expecting.  You might consider posting to the linux-usb mailing list and providing the host controller and device info.

**Comment by dickens** [comment]
Also, to further clarify, hitting the limit of usbfs_memory_mb would cause you to see LIBUSB_ERROR_NO_MEM.
