### ISSUE TITLE
I was able to edit the wikipage. 

### ISSUE THREAD

**Issue by DavidBM** [libusb/libusb#641]
I edited this one: https://github.com/libusb/libusb/wiki

Maybe there is permissions in order to avoid everyone to change things?

**Comment by LudovicRousseau** [comment]
Why is it a problem to edit a wiki page?

**Comment by DavidBM** [comment]
Because anyone can add malicious links, or delete everything, or add miss information.

**Comment by pbatard** [comment]
That's hardly an issue. Malicious edits can be reverted (the history can __not__ be deleted, so even if someone deletes the whole thing, all it takes is about one click to restore it).

It's much better to let people edit a Wiki so that they can add relevant information, than close it off and slowly make it less and less relevant as it becomes obsolete.

If you see malicious links or misinformation, you can either add your edits to revert them or signal it to the project maintainers.

**Comment by DavidBM** [comment]
Ok! 
The decision is yours. I will close this one. :)
