### ISSUE TITLE
Track send progress using libusb_bulk_transfer or libusb_fill_bulk_transfer.

### ISSUE THREAD

**Issue by ganeshrvel** [libusb/libusb#801]
How can I track the progress of data buffer transfer to the device while using libusb_fill_bulk_transfer or libusb_bulk_transfer?

**Comment by diabolo38** [comment]
you can't even in kernel driver it's not possible 
if for any valid  reason you need it send multiple smaller request instead of a  single big one 
this shall be fine until the  cut small request are still multiple of the end point max packet size 

Then you'll get intermediate call back/Completion not just the "big one"

**Comment by ganeshrvel** [comment]
shoot, that's going to be a heck slower!

**Comment by diabolo38** [comment]
if you use multiple assynch request you should get same or real close performances but system wise it's sure worst

**Comment by mcuee** [comment]
Please use libusb mailing list for question like this in the future. Thanks.
