### ISSUE TITLE
libusb_init calls SIGSTOP

### ISSUE THREAD

**Issue by zel1b08a** [libusb/libusb#809]
at qt debugging libusb_init(ctx) calls sigstop after update. but all works fine, i guess, on installed app.

**Comment by dickens** [comment]
I do not understand what you mean by "calls sigstop".  SIGSTOP is a symbolic name for a specific signal value--it isn't a function to "call".

In any case, the `libusb_init()` function does not send any signals, and as far as I know none of the functions that it calls will do so either.  If you are seeing this behavior, something else in your code is trapping one of the calls that libusb is making and generating this signal.  This isn't under the control of libusb, nor is it libusb's fault, so I'm going to close this issue.  If you find out some new information suggesting otherwise feel free to reopen this.
